# docker build -t mobz/elasticsearch-head:5-alpine -f Dockerfile-alpine .

FROM node:16.8.0-alpine3.13
WORKDIR /usr/src/app
RUN npm install http-server
COPY . .
EXPOSE 9100
CMD node_modules/http-server/bin/http-server _site -p 9100
